<div class="jumbotron">
<h2>POLS/CS&amp;SS 503: Advanced Quantitative Political Methodology</h2>
<h4>University of Washington, <small>Spring 2017</small></h4>
<br/>
<h4>Instructor: <a href="http://jrnold.io/">Jeffrey Arnold</a></h4>
<h4>TA: Daniel Yoo</h4>
</div>

# Overview

# Prerequisites


# Logistics

#### Teaching Team

<table class = "table table-striped">
<tr>
<td>
<strong>Primary</strong>
</td>
<td><a href="http://jrnold.me"><strong>Jeffrey Arnold</strong></a></td>
<td><a href="mailto:jrnold@uw.edu">jrnold@uw.edu</a></td>
</tr>
<tr>
<td>
<strong></strong>
</td>
<td>
<a href="">Daniel Yoo</a>
</td>
<td>
<a href="mailto:dhyoo@uw.edu">dhyoo@uw.edu</a>
</td>
</tr>
</table>

#### Meetings

<table class = "table table-striped table-hover">
<tr>
<td>Class </td>
<td>M,W </td>
<td>5:00&ndash;6:20 pm </td>
<td><a href="https://www.washington.edu/maps/?sav">SAV 117</td>
</tr>
<tr>
<td>Lab </td>
<td>F</td>
<td>1:30&ndash;3:20 pm </td>
<td><a href="https://www.washington.edu/maps/?cdh">SAV 117</a></td>
</tr>
</table>

#### Office Hours

<table class = "table table-striped">
<tr>
<td>Jeff Arnold</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>Daniel Yoo</td>
<td>F</td>
<td>3:30-4:20pm</td>
<td><a href="http://www.washington.edu/maps/#!/smi">SMI 220</a></td>
</tr>
</table>

Instructions for Jeff's office hours:

1. Sign up for a 30-minute slot using the Google Calendar appointments link emailed to the class.

2. Email me 24 hours prior to your appointment with what you would like to discuss.

These instructions will ensure that our time is efficiently spent and I can be of the most help to you.

#### Communication

In this course we will be using [Slack](https://slack.com/) for online class discussion. You will not be required to post, but the system is designed to get you help quickly and efficiently from classmates, and the instructors.
Rather than emailing questions to the instructors, post your questions to [https://uwpolsmethods.slack.com/](Slack).
You should have received an invitation to join this team, if not contact us to receive an invite.

# Evaluation

- Homework Assignments:
- Participation:


# Texts

The primary texts for this course are:

- Angrist, Joshua D. and Pischke, Jörn-Steffen. 2015. *[Mastering Metrics: The Path from Cause to Effect](https://www.amazon.com/Mastering-Metrics-Path-Cause-Effect/dp/0691152845/)*
- Bailey. 2015. *[Real Stats: Using Econometrics for Political Science and Public Policy](https://www.amazon.com/Real-Stats-Econometrics-Political-Science/dp/0199981949/).*

Additional readings are on the [schedule](schedule.html).

# Software

For computation, this course will rely upon [R](https://cran.r-project.org/): a language for statistical computing.

I expect that students will already be familiar with **R**, so class time will not be spent introducing it.
In particular, I expect students to be familiar with the material in [R for Data Science](http://r4ds.had.co.nz/). 
This covers the [tidyverse](http://tidyverse.org/) packages used in data wrangling: **ggplot**, **dplyr**, **tidyr**, **purrr**, **readr**, **haven**, **stringr**, and **forcats**.

Though not necessary, you are encouraged to use [RStudio](https://www.rstudio.com/products/rstudio/#Desktop) Desktop integrated development environment (IDE) for R.

# Bugs or Questions

If you find any problems in the syllabus or anthing else on this site either open an [issue](https://github.com/UW-POLS503/2017/issues) or fix the source and open a [pull request](https://github.com/UW-POLS503/2017/pulls).

# Rough Schedule of Topics

- Week 1
    - RS (Ch 1, 2, 3, 4)
    - What is regression?
    - Mechanics of OLS
    - Properties of least squares
    - Bias-variance tradeoff
    - Inference
    - Git
- Week 2
    - Gauss-Markov Theorem
    - Omitted Variables (RS: Ch 14)
    - Matrix algebra
    - Multivariate Regression (RS: Ch 5)
    - Inference for multivariate regression
- Week 3
    - Dummy variables - (RS: Ch 6)
    - Interactions - 
    - Inference for multiple coefficients
- Week 4
    - Outliers / influential points
    - Heteroskedasticity
    - Functional Form
    - Bootstrap
    - NHST - research replication
    - substantive significance
- Week 5
    - Mastering Metrics (MM Ch 1)
    - Potential Outcomes
    - Experiments
- Week 6
    - Matching / Selection on Observables (MM Ch 2, 6.1)
- Week 7
    - Instrumental Variables (MM Ch 3, 6.2)
- Week 8
    - Regression Discontinuity (MM Ch 4, 6.3)
- Week 9
    - Panel data (MM Ch 5)
- Week 10
    - Prediction
    - Lasso
    - Cross Validation
